name: "Archive Issues and Pull Requests"

on:
  schedule:
    - cron: '0 0 * * 0,2,4'
  repository_dispatch:
    types: [archive]
  workflow_dispatch:
    inputs:
      archive_full:
        description: 'Recreate the archive from scratch'
        default: false
        type: boolean

jobs:
  build:
    name: "Archive Issues and Pull Requests"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    # Note: No caching for this build!

    - name: "Update Archive"
      uses: martinthomson/i-d-template@v1
      env:
        ARCHIVE_FULL: ${{ inputs.archive_full }}
      with:
        make: archive
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      with:
        make: gh-archive
        token: ${{ github.token }}

    - name: "Save Archive"
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
      with:
        path: archive.json
